services:
  api-proxy:
    build:
      dockerfile: ./Dockerfile
    pull_policy: build
    container_name: api-proxy
    image: api-proxy:latest
    restart: always
    ports:
      - "127.0.0.1:8070:8000"
    environment:
      - WISE_API_TOKEN=${WISE_API_TOKEN}
